### ISSUE TITLE
master to main

### ISSUE THREAD

**Issue by wNv-paCe** [warsylewicz/webdev2-community-events#1]
Hi Aaron, is it possible to change the branch master to main? lol

**Comment by warsylewicz** [comment]
Yes, it is possible to rename. I'll consider doing that when the semester is over. If I were to do it now, everyone that has cloned the repository would need to update their clone. I cannot expect all students to do the following right now: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes
